name: Vercel Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: vercel-deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run build
      - uses: amondnet/vercel-action@v25.1.0
        with:
          github-token: ${{ secrets.TOKEN}}
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}} #Required
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}} #Required
          working-directory: ./sub-directory
