name: Vercel Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: vercel-deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run build
      - uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.TOKEN}}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }} # Required
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID}} #Required
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID}} #Required
          working-directory: ./sub-directory
